// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vgveowewqmozvtjkmefl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZndmVvd2V3cW1venZ0amttZWZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAwNTIwOTgsImV4cCI6MjA4NTYyODA5OH0.HyDD0MJvE9gSnuothIJ5EbtWOTIcgU9UX1-jO8kht5g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});